"""
Convert a SQLAlchemy 2.0 DeclarativeBase models file (generated by sqlacodegen)
into a Flask-SQLAlchemy `db.Model` based models.py file.

Usage: (from backend/scripts folder)
  python convert_models_sql2_to_flask.py \
    --in ../app/shared/models_sql2orm_plain_sqlalchemy2.py \
    --out ../app/shared/models_plain_sqlalchemy22flask_sqlalchemy.py

Both args are optional, defaults to above paths. Standard of Python
files is to use underscores "_" not hyphens "-", in order to be able
to import them directly without using importlib and other libs. 
This is a best-effort text transformation. Review the output and adjust
relationship/back_populates/uselist/foreign_keys or imports as needed.

The script: 
- replaces `class X(Base):` with `class X(db.Model):`
- replaces `mapped_column(TYPE, ...)` with `db.Column(db.TYPE, ...)` (best effort)
- replaces `Mapped[...]` annotated attributes with plain assignments
- changes `relationship(...)` -> `db.relationship(...)`
- keeps __table_args__ (ForeignKeyConstraint / Index) intact and imports text/Index if present

It is not guaranteed to handle every edge case; inspect the result
"""

import argparse
import re
from pathlib import Path


import debugpy, os, sys
print("PID:", os.getpid(), file=sys.stderr, flush=True)
print("sys.executable:", sys.executable, file=sys.stderr, flush=True)
print("__file__:", __file__, file=sys.stderr, flush=True)
debugpy.listen(("0.0.0.0", 5678))
print("Waiting for debugger on 5678...",file=sys.stderr, flush=True)
debugpy.wait_for_client()
print("Debugger attached", file=sys.stderr, flush=True)
debugpy.breakpoint()


def transform_mapped_column_args(inner: str) -> str:
    """Convert the inner of mapped_column(...) into db.Column(...) string.
    Example: "Integer, primary_key=True" -> "db.Column(db.Integer, primary_key=True)"
    If no type provided (starts with identifier like primary_key=) produce db.Column(...)
    """
    s = inner.strip()
    if not s:
        return "db.Column()"

    # find end of first argument respecting parentheses
    pos = 0
    depth = 0
    found_first = False
    # enumerate(s): Builds an iterable that yields pairs of (i: index, ch: character)
    # for each character in string s
    for i, ch in enumerate(s):
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        elif ch == ',' and depth == 0:
            pos = i
            found_first = True
            break
    if found_first:
        # s[:pos]: Extract substring from start to pos (not including pos)
        first = s[:pos].strip()
        rest = s[pos+1:].strip()
    else:
        # only one arg or no commas
        first = s
        rest = ''

    # Determine if first looks like a type (identifier or IDENT(params)) or a kwarg
    # r: Tells Python to treat backslashes as literal characters, not escape characters
    # ^: Caret, start of string, $: End of string
    # .*\: Matches any character (.) zero or more times (*)
    # ?: Makes the preceding quantifier non-greedy, meaning it will match as few characters as possible
    if re.match(r'^[_A-Za-z][_A-Za-z0-9]*(\(.*\))?$', first):
        type_expr = first
        # prefix db. if not already
        if not type_expr.startswith('db.') and not type_expr.startswith('sqlalchemy.') and not type_expr.startswith('sa.'):
            type_expr = 'db.' + type_expr
        args = f"{type_expr}"
        if rest:
            args = args + ', ' + rest
        return f"db.Column({args})"
    else:
        # first is probably a kwarg, no explicit type
        return f"db.Column({s})"


def convert_file(src: Path, dst: Path) -> None:
    text = src.read_text(encoding='utf-8')

    # remove the DeclarativeBase import line
    # \s+: represents one or more whitespace characters (spaces, tabs, newlines)
    # re.sub(pattern, replacement, string) replaces occurrences of pattern in string with replacement
    text = re.sub(r"from\s+sqlalchemy\.orm\s+import\s+DeclarativeBase,?\s*Mapped,?\s*mapped_column,?\s*relationship\s*\n", '', text)
    # remove explicit DeclarativeBase class if present
    text = re.sub(r"class\s+Base\s*\(DeclarativeBase\):\s*\n\s*pass\s*\n\n", '', text)

    # add Flask-SQLAlchemy db import
    header = "from .database import db\n"

    # if file already has a module docstring or top imports, try to insert after them
    # simple approach: replace first occurrence of 'class ' with header before it
    # Issue?: It's not doing that, just prepending header at top
    if 'from .database import db' not in text:
        # place header at top
        text = header + text

    # Replace class inheritance Base -> db.Model
    # \1: Backreference to first captured group (class name)
    # \w+: Matches one or more word characters (class name)
    # (\w+): Captures the first group (class name) for reuse in replacement 
    text = re.sub(r"class\s+(\w+)\s*\(\s*Base\s*\):", r"class \1(db.Model):", text)

    # Replace Mapped annotated mapped_column assignments
    # pattern: name: Mapped[...]= mapped_column(...)
    # .compile(): precompiles the regex for efficiency, this is useful if the regex is used multiple times
    # (): Capturing groups to extract parts of the match
    # \[[^\]]+\]: Matches an opening bracket with \[, followed by one or more characters that are not a
    # closing bracket (using [^\]]+ this is called a negated character class), and then a closing
    # bracket with \]
    # [^\]]+ called negated character: "[" begin char class, "^" after "[" negates the class, except
    # listed chars, in this case "]" with "\]" (escaped), then "]" to close char class
    # .*?: Matches any character (.), zero or more times (*), but as few times as possible (?),
    # until first ")", represented by "\)"
    # re.MULTILINE: Allows ^ and $ to match the start and end of each line
    # re.DOTALL: Makes the dot (.) match newline characters as well, so it can span multiple lines.
    # Using a more tolerant capture for the Mapped[...] part so it can span
    # multiple lines and include nested generics. DOTALL lets '.' match newlines
    # and the non-greedy (.*?) stops at the first closing ']'. This is best-effort
    # and more permissive than the previous [^\]]+ which failed on nested brackets
    pattern = re.compile(r"^(\s*)([A-Za-z_][A-Za-z0-9_]*)\s*:\s*Mapped\[(.*?)\]\s*=\s*mapped_column\((.*?)\)\s*$", re.MULTILINE | re.DOTALL)
    
    def repl_mapped(match):
        indent = match.group(1)
        name = match.group(2)
        # After changing the Mapped[...] part to a separate non-greedy capture,
        # groups are now: 1=indent, 2=name, 3=Mapped[...] content, 4=mapped_column inner args
        inner = match.group(4)
        print("match:", match, file=sys.stderr, flush=True)
        print("match.group(4):", match.group(4), file=sys.stderr, flush=True)
        col = transform_mapped_column_args(inner)
        return f"{indent}{name} = {col}"

    # Here repl_mapped is called for each match found by pattern.sub in text. Each match is received in the function's
    # 'match' argument
    # pattern.sub(repl_mapped, text): Applies the regex pattern to the text and replaces matches
    # using repl_mapped function. This usage is a little different from the earlier re.sub usage
    # because pattern is already a compiled regex object
    text = pattern.sub(repl_mapped, text)

    # Handle cases where mapped_column is on multiple lines (simplistic): collapse mapped_column( ... ) to single line
    # lambda m: Corresponds to an anonymous inline small function in Python that takes a match object m and
    # returns a transformed string
    # Collapse two-lines mapped_column(...) into a single-line call
    text = re.sub(r"mapped_column\((\s*[^)]*?)\)(\s*)",
                  lambda m: "mapped_column({})".format(m.group(1).replace('\n', ' ').strip()),
                  text)

    # Replace remaining occurrences of mapped_column(...) that were created above or missed
    text = re.sub(r"mapped_column\((.*?)\)", lambda m: transform_mapped_column_args(m.group(1)), text, flags=re.DOTALL)

    # Replace relationship(...) -> db.relationship(...)
    # \b: Asserts a word boundary, ensuring we match 'relationship' as a whole word
    text = re.sub(r"\brelationship\s*\(", "db.relationship(", text)

    # Replace type references like Integer -> db.Integer inside any remaining mapped_column args or Column defs
    # This is best-effort: prefix common SQLAlchemy type names with db. when they appear as standalone identifiers
    types = ['Integer','BigInteger','String','Text','JSON','DECIMAL','Date','DateTime','TIMESTAMP','Float','Numeric','Boolean']
    for t in types:
        # Only match the bare identifier when it's NOT already prefixed with db., sa., or sqlalchemy.
        # Use multiple fixed-width negative lookbehinds (eg: (?<!db\.)(?<!sa\.)(?<!sqlalchemy\.))
        type_pattern = rf"(?<!db\.)(?<!sa\.)(?<!sqlalchemy\.)\b{t}\b"
        text = re.sub(type_pattern, f"db.{t}", text)

    # Replace mapped_column markers if any left
    text = text.replace('mapped_column', 'db.Column')

    # Replace typing annotations for relationships like: var: Mapped[list['X']] = relationship(...) -> var = db.relationship(...)
    rel_pattern = re.compile(r"^(\s*)([A-Za-z_][A-Za-z0-9_]*)\s*:\s*Mapped\[[^\]]+\]\s*=\s*db\.relationship\((.*?)\)\s*$", re.MULTILINE | re.DOTALL)
    def repl_rel(m):
        indent, name, inner = m.group(1), m.group(2), m.group(3)
        return f"{indent}{name} = db.relationship({inner})"
    text = rel_pattern.sub(repl_rel, text)

    # Clean up excessive blank lines
    # {3,}: Matches 3 or more newline characters, no upper limit
    text = re.sub(r"\n{3,}", "\n\n", text)

    dst.write_text(text, encoding='utf-8')
    print(f"Converted {src} -> {dst}")


def main():
    # argparse.ArgumentParser: Creates a new argument parser object
    parser = argparse.ArgumentParser()
    # add_argument: Adds a new argument to the parser
    parser.add_argument('--in', dest='src', default='../app/shared/models_sql2orm_plain_sqlalchemy2.py')
    parser.add_argument('--out', dest='dst', default='../app/shared/models_plain_sqlalchemy22flask_sqlalchemy.py')
    # parse_args: Parses the command-line arguments
    args = parser.parse_args()
    # Path: Represents a filesystem path
    src = Path(args.src)
    dst = Path(args.dst)
    if not src.exists():
        print('Source file not found:', src)
        return
    convert_file(src, dst)

# When script runs directly, eg. python convert_models_sql2_to_flask then name is set to '__main__'
# When script is imported as a module, name is set to the module's name. eg. 'convert_models_sqlalchemy22flask-sqlalchemy'
if __name__ == '__main__':
    main()
