"""1st Alembic: models2SQL Attempt

Revision ID: 85cd3b1ae04c
Revises: 
Create Date: 2025-10-02 12:06:18.710567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '85cd3b1ae04c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_statuses',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('status_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('status_code')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_code')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_description', sa.Text(), nullable=True),
    sa.Column('category_pic_path', sa.String(length=255), nullable=True),
    sa.Column('category_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_status_id'], ['entity_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_status_id'], ['entity_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('products_services',
    sa.Column('product_service_id', sa.Integer(), nullable=False),
    sa.Column('product_service_name', sa.String(length=100), nullable=False),
    sa.Column('product_service_description', sa.Text(), nullable=True),
    sa.Column('product_service_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_service_status_id'], ['entity_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('product_service_id'),
    sa.UniqueConstraint('product_service_name')
    )
    op.create_table('stores',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('store_email', sa.String(length=100), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('store_description', sa.Text(), nullable=True),
    sa.Column('store_phone', sa.String(length=20), nullable=True),
    sa.Column('store_address', sa.Text(), nullable=True),
    sa.Column('store_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_status_id'], ['entity_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('store_email')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_phone', sa.String(length=20), nullable=True),
    sa.Column('user_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_status_id'], ['entity_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('store_products_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_service_id'], ['products_services.product_service_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_user_role',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['entity_statuses.status_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('store_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_user_role')
    op.drop_table('store_products_services')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('products_services')
    op.drop_table('customers')
    op.drop_table('categories')
    op.drop_table('roles')
    op.drop_table('entity_statuses')
    # ### end Alembic commands ###
