# Dockerfile for backend-search service
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

ARG SEARCH_ENGINE=meili

# Remove any existing search directory
RUN rm -rf ./app/shared/search
# Copy only the chosen search backend
COPY ./app/shared/search_${SEARCH_ENGINE} ./search

# Expose port for search service (just for documentation purpose)
# EXPOSE 5002

# Entrypoint for search service (runs only the search API)
# CMD ["gunicorn", "--workers=2", "--bind=0.0.0.0:5002", "app.shared.search_wsgi:app"]
