"""1st Alembic: models2SQL Attempt

Revision ID: 1a606a1405ab
Revises: 
Create Date: 2025-09-30 00:59:58.723995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic
revision: str = '1a606a1405ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_user_role')
    op.drop_table('customer_addresses')
    op.drop_index(op.f('state_region_code'), table_name='states_regions')
    op.drop_table('states_regions')
    op.drop_index(op.f('status_code'), table_name='entity_statuses')
    op.drop_table('entity_statuses')
    op.drop_table('states_regions_history')
    op.drop_table('customer_addresses_history')
    op.drop_index(op.f('store_email'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('status_code'), table_name='order_statuses')
    op.drop_table('order_statuses')
    op.drop_table('cities_history')
    op.drop_table('stores_history')
    op.drop_table('order_details')
    op.drop_index(op.f('user_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('orders_history')
    op.drop_table('entity_statuses_history')
    op.drop_table('customers_history')
    op.drop_index(op.f('role_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('country_code'), table_name='countries')
    op.drop_table('countries')
    op.drop_table('categories_history')
    op.drop_index(op.f('customer_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('store_products_services_history')
    op.drop_table('cities')
    op.drop_index(op.f('idx_users_history_time'), table_name='users_history')
    op.drop_index(op.f('idx_users_history_user'), table_name='users_history')
    op.drop_table('users_history')
    op.drop_table('roles_history')
    op.drop_index(op.f('category_name'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('order_statuses_history')
    op.drop_table('store_user_role_history')
    op.drop_table('products_services_history')
    op.drop_table('countries_history')
    op.drop_index(op.f('idx_product_service'), table_name='store_products_services')
    op.drop_index(op.f('idx_store'), table_name='store_products_services')
    op.drop_index(op.f('uk_store_product'), table_name='store_products_services')
    op.drop_table('store_products_services')
    op.drop_table('order_details_history')
    op.drop_index(op.f('product_service_name'), table_name='products_services')
    op.drop_table('products_services')
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_tot_quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_tot_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name='orders_ibfk_1'),
    sa.ForeignKeyConstraint(['order_status_id'], ['order_statuses.status_id'], name='orders_ibfk_2'),
    sa.PrimaryKeyConstraint('order_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('products_services',
    sa.Column('product_service_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_service_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('product_service_description', mysql.TEXT(), nullable=True),
    sa.Column('product_service_pic_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('product_service_category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_service_status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_service_category_id'], ['categories.category_id'], name='products_services_ibfk_1'),
    sa.ForeignKeyConstraint(['product_service_status_id'], ['entity_statuses.status_id'], name='products_services_ibfk_2'),
    sa.PrimaryKeyConstraint('product_service_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('product_service_name'), 'products_services', ['product_service_name'], unique=True)
    op.create_table('order_details_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_product_service_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('store_products_services',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_service_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_service_id'], ['products_services.product_service_id'], name='store_products_services_ibfk_3'),
    sa.ForeignKeyConstraint(['status_id'], ['entity_statuses.status_id'], name='store_products_services_ibfk_1'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], name='store_products_services_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uk_store_product'), 'store_products_services', ['store_id', 'product_service_id'], unique=True)
    op.create_index(op.f('idx_store'), 'store_products_services', ['store_id'], unique=False)
    op.create_index(op.f('idx_product_service'), 'store_products_services', ['product_service_id'], unique=False)
    op.create_table('countries_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('country_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('products_services_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_service_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('store_user_role_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('store_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('order_statuses_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('status_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categories',
    sa.Column('category_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('category_description', mysql.TEXT(), nullable=True),
    sa.Column('category_pic_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('category_status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_status_id'], ['entity_statuses.status_id'], name='categories_ibfk_1'),
    sa.PrimaryKeyConstraint('category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('category_name'), 'categories', ['category_name'], unique=True)
    op.create_table('roles_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_users_history_user'), 'users_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_users_history_time'), 'users_history', ['changed_at'], unique=False)
    op.create_table('cities',
    sa.Column('city_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('state_region_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city_status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_status_id'], ['entity_statuses.status_id'], name='cities_ibfk_2'),
    sa.ForeignKeyConstraint(['state_region_id'], ['states_regions.state_region_id'], name='cities_ibfk_1'),
    sa.PrimaryKeyConstraint('city_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('store_products_services_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_service_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('customers',
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('customer_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('customer_password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('customer_phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('customer_status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_status_id'], ['entity_statuses.status_id'], name='customers_ibfk_1'),
    sa.PrimaryKeyConstraint('customer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('customer_email'), 'customers', ['customer_email'], unique=True)
    op.create_table('categories_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('countries',
    sa.Column('country_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('country_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('country_status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_status_id'], ['entity_statuses.status_id'], name='countries_ibfk_1'),
    sa.PrimaryKeyConstraint('country_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('country_code'), 'countries', ['country_code'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('role_description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('role_code'), 'roles', ['role_code'], unique=True)
    op.create_table('customers_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('entity_statuses_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('status_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orders_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('user_status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_status_id'], ['entity_statuses.status_id'], name='users_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('user_email'), 'users', ['user_email'], unique=True)
    op.create_table('order_details',
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('store_product_service_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_service_quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_service_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('product_service_tot_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('product_service_status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_service_filled_quantity', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('product_service_filled_tot_price', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('order_details_ibfk_2')),
    sa.ForeignKeyConstraint(['product_service_status_id'], ['order_statuses.status_id'], name=op.f('order_details_ibfk_1')),
    sa.ForeignKeyConstraint(['store_product_service_id'], ['store_products_services.id'], name=op.f('order_details_ibfk_3')),
    sa.PrimaryKeyConstraint('order_id', 'store_product_service_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('stores_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('store_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cities_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('city_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('order_statuses',
    sa.Column('status_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status_description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('status_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('status_code'), 'order_statuses', ['status_code'], unique=True)
    op.create_table('stores',
    sa.Column('store_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('store_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('store_description', mysql.TEXT(), nullable=True),
    sa.Column('store_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('store_address', mysql.TEXT(), nullable=False),
    sa.Column('store_status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['store_status_id'], ['entity_statuses.status_id'], name='stores_ibfk_1'),
    sa.PrimaryKeyConstraint('store_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('store_email'), 'stores', ['store_email'], unique=True)
    op.create_table('customer_addresses_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('address_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('states_regions_history',
    sa.Column('hist_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('state_region_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('op_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_before', mysql.JSON(), nullable=True),
    sa.Column('data_after', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('entity_statuses',
    sa.Column('status_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status_description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('status_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('status_code'), 'entity_statuses', ['status_code'], unique=True)
    op.create_table('states_regions',
    sa.Column('state_region_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state_region_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('state_region_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('country_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state_region_status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], name='states_regions_ibfk_1'),
    sa.ForeignKeyConstraint(['state_region_status_id'], ['entity_statuses.status_id'], name='states_regions_ibfk_2'),
    sa.PrimaryKeyConstraint('state_region_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('state_region_code'), 'states_regions', ['state_region_code'], unique=True)
    op.create_table('customer_addresses',
    sa.Column('address_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address_line1', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('address_line2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('google_maps_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('address_status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('postal_code', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['address_status_id'], ['entity_statuses.status_id'], name=op.f('customer_addresses_ibfk_3')),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], name=op.f('customer_addresses_ibfk_2')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('customer_addresses_ibfk_1')),
    sa.PrimaryKeyConstraint('address_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('store_user_role',
    sa.Column('store_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('store_user_role_ibfk_3')),
    sa.ForeignKeyConstraint(['status_id'], ['entity_statuses.status_id'], name=op.f('store_user_role_ibfk_4')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], name=op.f('store_user_role_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('store_user_role_ibfk_2')),
    sa.PrimaryKeyConstraint('store_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
