"""1st Alembic: models2SQL Attempt

Revision ID: 7ec7b65c7a98
Revises: 
Create Date: 2025-10-28 14:55:06.632800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '7ec7b65c7a98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('category_id', 'categories_history', ['category_id'], unique=False)
    op.create_index('changed_at', 'categories_history', ['changed_at'], unique=False)
    op.create_table('cities_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('changed_at', 'cities_history', ['changed_at'], unique=False)
    op.create_index('city_id', 'cities_history', ['city_id'], unique=False)
    op.create_table('countries_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('changed_at', 'countries_history', ['changed_at'], unique=False)
    op.create_index('country_id', 'countries_history', ['country_id'], unique=False)
    op.create_table('customer_addresses_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('address_id', 'customer_addresses_history', ['address_id'], unique=False)
    op.create_index('changed_at', 'customer_addresses_history', ['changed_at'], unique=False)
    op.create_index('customer_id', 'customer_addresses_history', ['customer_id'], unique=False)
    op.create_table('customers_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('changed_at', 'customers_history', ['changed_at'], unique=False)
    op.create_index('customer_id', 'customers_history', ['customer_id'], unique=False)
    op.create_table('entity_statuses',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('status_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_index('status_code', 'entity_statuses', ['status_code'], unique=True)
    op.create_table('entity_statuses_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('changed_at', 'entity_statuses_history', ['changed_at'], unique=False)
    op.create_index('status_id', 'entity_statuses_history', ['status_id'], unique=False)
    op.create_table('order_details_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('store_product_service_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('changed_at', 'order_details_history', ['changed_at'], unique=False)
    op.create_index('order_id', 'order_details_history', ['order_id'], unique=False)
    op.create_index('store_product_service_id', 'order_details_history', ['store_product_service_id'], unique=False)
    op.create_table('order_statuses',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('status_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_index('status_code', 'order_statuses', ['status_code'], unique=True)
    op.create_table('order_statuses_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('changed_at', 'order_statuses_history', ['changed_at'], unique=False)
    op.create_index('status_id', 'order_statuses_history', ['status_id'], unique=False)
    op.create_table('orders_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('changed_at', 'orders_history', ['changed_at'], unique=False)
    op.create_index('order_id', 'orders_history', ['order_id'], unique=False)
    op.create_table('products_services_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('product_service_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('changed_at', 'products_services_history', ['changed_at'], unique=False)
    op.create_index('product_service_id', 'products_services_history', ['product_service_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index('role_code', 'roles', ['role_code'], unique=True)
    op.create_table('roles_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('changed_at', 'roles_history', ['changed_at'], unique=False)
    op.create_index('role_id', 'roles_history', ['role_id'], unique=False)
    op.create_table('states_regions_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('state_region_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('changed_at', 'states_regions_history', ['changed_at'], unique=False)
    op.create_index('state_region_id', 'states_regions_history', ['state_region_id'], unique=False)
    op.create_table('store_products_services_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('product_service_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('changed_at', 'store_products_services_history', ['changed_at'], unique=False)
    op.create_index('id', 'store_products_services_history', ['id'], unique=False)
    op.create_index('product_service_id', 'store_products_services_history', ['product_service_id'], unique=False)
    op.create_index('store_id', 'store_products_services_history', ['store_id'], unique=False)
    op.create_table('store_user_role_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('changed_at', 'store_user_role_history', ['changed_at'], unique=False)
    op.create_index('store_id', 'store_user_role_history', ['store_id'], unique=False)
    op.create_index('user_id', 'store_user_role_history', ['user_id'], unique=False)
    op.create_table('stores_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('changed_at', 'stores_history', ['changed_at'], unique=False)
    op.create_index('store_id', 'stores_history', ['store_id'], unique=False)
    op.create_table('users_history',
    sa.Column('hist_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.Enum('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('data_before', sa.JSON(), nullable=True),
    sa.Column('data_after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_index('idx_users_history_time', 'users_history', ['changed_at'], unique=False)
    op.create_index('idx_users_history_user', 'users_history', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_description', sa.Text(), nullable=True),
    sa.Column('category_pic_path', sa.String(length=255), nullable=True),
    sa.Column('category_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_status_id'], ['entity_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index('category_name', 'categories', ['category_name'], unique=True)
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('country_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_status_id'], ['entity_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_index('country_code', 'countries', ['country_code'], unique=True)
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_email', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_password_hash', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_status_id'], ['entity_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index('customer_email', 'customers', ['customer_email'], unique=True)
    op.create_table('stores',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('store_email', sa.String(length=100), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('store_description', sa.Text(), nullable=True),
    sa.Column('store_phone', sa.String(length=20), nullable=True),
    sa.Column('store_address', sa.Text(), nullable=False),
    sa.Column('store_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_status_id'], ['entity_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index('store_email', 'stores', ['store_email'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_phone', sa.String(length=20), nullable=False),
    sa.Column('user_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_status_id'], ['entity_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('user_email', 'users', ['user_email'], unique=True)
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_tot_quantity', sa.Integer(), nullable=False),
    sa.Column('order_tot_price', sa.Numeric(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['order_status_id'], ['order_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('products_services',
    sa.Column('product_service_id', sa.Integer(), nullable=False),
    sa.Column('product_service_name', sa.String(length=100), nullable=False),
    sa.Column('product_service_description', sa.Text(), nullable=True),
    sa.Column('product_service_pic_path', sa.String(length=255), nullable=True),
    sa.Column('product_service_category_id', sa.Integer(), nullable=False),
    sa.Column('product_service_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_service_category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['product_service_status_id'], ['entity_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('product_service_id')
    )
    op.create_index('product_service_name', 'products_services', ['product_service_name'], unique=True)
    op.create_table('states_regions',
    sa.Column('state_region_id', sa.Integer(), nullable=False),
    sa.Column('state_region_name', sa.String(length=100), nullable=False),
    sa.Column('state_region_code', sa.String(length=10), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('state_region_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.ForeignKeyConstraint(['state_region_status_id'], ['entity_statuses.status_id'], ),
    sa.PrimaryKeyConstraint('state_region_id')
    )
    op.create_index('state_region_code', 'states_regions', ['state_region_code'], unique=True)
    op.create_table('store_user_role',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['entity_statuses.status_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('store_id', 'user_id')
    )
    op.create_table('cities',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('state_region_id', sa.Integer(), nullable=False),
    sa.Column('city_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_status_id'], ['entity_statuses.status_id'], ),
    sa.ForeignKeyConstraint(['state_region_id'], ['states_regions.state_region_id'], ),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('store_products_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_service_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_service_id'], ['products_services.product_service_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['entity_statuses.status_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uk_store_product', 'store_products_services', ['store_id', 'product_service_id'], unique=True)
    op.create_table('customer_addresses',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('google_maps_url', sa.String(length=255), nullable=False),
    sa.Column('address_status_id', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['address_status_id'], ['entity_statuses.status_id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('order_details',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('store_product_service_id', sa.Integer(), nullable=False),
    sa.Column('product_service_quantity', sa.Integer(), nullable=False),
    sa.Column('product_service_price', sa.Numeric(), nullable=False),
    sa.Column('product_service_tot_price', sa.Numeric(), nullable=False),
    sa.Column('product_service_status_id', sa.Integer(), nullable=False),
    sa.Column('product_service_filled_quantity', sa.Integer(), nullable=False),
    sa.Column('product_service_filled_tot_price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_service_status_id'], ['order_statuses.status_id'], ),
    sa.ForeignKeyConstraint(['store_product_service_id'], ['store_products_services.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'store_product_service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('customer_addresses')
    op.drop_index('uk_store_product', table_name='store_products_services')
    op.drop_table('store_products_services')
    op.drop_table('cities')
    op.drop_table('store_user_role')
    op.drop_index('state_region_code', table_name='states_regions')
    op.drop_table('states_regions')
    op.drop_index('product_service_name', table_name='products_services')
    op.drop_table('products_services')
    op.drop_table('orders')
    op.drop_index('user_email', table_name='users')
    op.drop_table('users')
    op.drop_index('store_email', table_name='stores')
    op.drop_table('stores')
    op.drop_index('customer_email', table_name='customers')
    op.drop_table('customers')
    op.drop_index('country_code', table_name='countries')
    op.drop_table('countries')
    op.drop_index('category_name', table_name='categories')
    op.drop_table('categories')
    op.drop_index('idx_users_history_user', table_name='users_history')
    op.drop_index('idx_users_history_time', table_name='users_history')
    op.drop_table('users_history')
    op.drop_index('store_id', table_name='stores_history')
    op.drop_index('changed_at', table_name='stores_history')
    op.drop_table('stores_history')
    op.drop_index('user_id', table_name='store_user_role_history')
    op.drop_index('store_id', table_name='store_user_role_history')
    op.drop_index('changed_at', table_name='store_user_role_history')
    op.drop_table('store_user_role_history')
    op.drop_index('store_id', table_name='store_products_services_history')
    op.drop_index('product_service_id', table_name='store_products_services_history')
    op.drop_index('id', table_name='store_products_services_history')
    op.drop_index('changed_at', table_name='store_products_services_history')
    op.drop_table('store_products_services_history')
    op.drop_index('state_region_id', table_name='states_regions_history')
    op.drop_index('changed_at', table_name='states_regions_history')
    op.drop_table('states_regions_history')
    op.drop_index('role_id', table_name='roles_history')
    op.drop_index('changed_at', table_name='roles_history')
    op.drop_table('roles_history')
    op.drop_index('role_code', table_name='roles')
    op.drop_table('roles')
    op.drop_index('product_service_id', table_name='products_services_history')
    op.drop_index('changed_at', table_name='products_services_history')
    op.drop_table('products_services_history')
    op.drop_index('order_id', table_name='orders_history')
    op.drop_index('changed_at', table_name='orders_history')
    op.drop_table('orders_history')
    op.drop_index('status_id', table_name='order_statuses_history')
    op.drop_index('changed_at', table_name='order_statuses_history')
    op.drop_table('order_statuses_history')
    op.drop_index('status_code', table_name='order_statuses')
    op.drop_table('order_statuses')
    op.drop_index('store_product_service_id', table_name='order_details_history')
    op.drop_index('order_id', table_name='order_details_history')
    op.drop_index('changed_at', table_name='order_details_history')
    op.drop_table('order_details_history')
    op.drop_index('status_id', table_name='entity_statuses_history')
    op.drop_index('changed_at', table_name='entity_statuses_history')
    op.drop_table('entity_statuses_history')
    op.drop_index('status_code', table_name='entity_statuses')
    op.drop_table('entity_statuses')
    op.drop_index('customer_id', table_name='customers_history')
    op.drop_index('changed_at', table_name='customers_history')
    op.drop_table('customers_history')
    op.drop_index('customer_id', table_name='customer_addresses_history')
    op.drop_index('changed_at', table_name='customer_addresses_history')
    op.drop_index('address_id', table_name='customer_addresses_history')
    op.drop_table('customer_addresses_history')
    op.drop_index('country_id', table_name='countries_history')
    op.drop_index('changed_at', table_name='countries_history')
    op.drop_table('countries_history')
    op.drop_index('city_id', table_name='cities_history')
    op.drop_index('changed_at', table_name='cities_history')
    op.drop_table('cities_history')
    op.drop_index('changed_at', table_name='categories_history')
    op.drop_index('category_id', table_name='categories_history')
    op.drop_table('categories_history')
    # ### end Alembic commands ###
